services:
  discord-bot:
    build: 
      context: .
      args:
        CA_SERVER_URL: "${CA_SERVER_URL}"
        SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"
    container_name: amber-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-0}
    env_file:
      - .env
    ports:
      - "${PROMETHEUS_PORT:-5150}:${PROMETHEUS_PORT:-5150}"  # Prometheus metrics endpoint
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - discord-bot-network
    mem_limit: 512m
    cpus: 0.5
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=${PROMETHEUS_PORT:-5150}"
      - "prometheus.io/path=/metrics"

networks:
  discord-bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local