apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amber-data-pvc
  namespace: amber
  labels:
    app: discord-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default