apiVersion: v1
kind: Service
metadata:
  name: amber-discord-bot
  namespace: amber
  labels:
    app: discord-bot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: health
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: discord-bot
---
apiVersion: v1
kind: Service
metadata:
  name: amber-metrics
  namespace: amber
  labels:
    app: discord-bot
    component: metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: discord-bot