# GitOps Configuration - Disabled until agent version supports it
# Reference: https://docs.gitlab.com/user/clusters/agent/gitops.html
# gitops:
#   manifest_projects:
#   - id: baguilartech/amber
#     default_namespace: amber
#     paths:
#     - glob: 'k8s/**/*.yaml'
#     - glob: 'k8s/**/*.yml'
#     reconcile_timeout: 3600s
#     dry_run_strategy: none
#     prune: true
#     prune_timeout: 3600s
#     prune_propagation_policy: foreground
#     inventory_policy: must_match

# CI/CD Access - Allow GitLab CI/CD jobs to deploy to cluster
# Reference: https://docs.gitlab.com/user/clusters/agent/ci_cd_workflow.html
ci_access:
  projects:
  - id: discord-bots/Amber
    access_as:
      agent: {}
  groups:
  - id: discord-bots
    access_as:
      agent: {}

observability:
  logging:
    level: info
  # gitops:
  #   log_level: info

remote_development:
  enabled: false

# User Access - Allow GitLab users to access Kubernetes via GitLab UI
# Users with Developer+ role can run kubectl commands through GitLab
# Reference: https://docs.gitlab.com/user/clusters/agent/user_access/
user_access:
  access_as:
    agent: {}
  projects:
  - id: discord-bots/Amber
  groups:
  - id: discord-bots

flux:
  enabled: false 