name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          if [ -n "${{ secrets.SENTRY_AUTH_TOKEN }}" ]; then
            npm run build
          else
            echo "SENTRY_AUTH_TOKEN not available, building without Sentry sourcemaps"
            tsc
          fi
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: sentry
          SENTRY_PROJECT: amber-discord-bot
        
      - name: Run tests
        run: npm run test:ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Release notes for version ${{ steps.get_version.outputs.VERSION }}
            
            ## Changes
            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
            
            ## Docker Image
            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/amber:${{ steps.get_version.outputs.VERSION }}
            docker pull ghcr.io/${{ github.repository_owner }}/amber:latest
            ```
          draft: false
          prerelease: false
          
      - name: Build Docker image
        run: |
          docker build --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} -t ghcr.io/${{ github.repository_owner }}/amber:${{ steps.get_version.outputs.VERSION }} .
          docker build --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} -t ghcr.io/${{ github.repository_owner }}/amber:latest .
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/amber:${{ steps.get_version.outputs.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('trivy-results.sarif') != ''
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Run Trivy vulnerability scanner (table output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/amber:${{ steps.get_version.outputs.VERSION }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/amber:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/amber:latest
          
      - name: Publish NPM package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}