name: Publish Wiki

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Clone wiki repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-repo
      
      - name: Check for wiki changes
        run: |
          # Check if wiki directory exists and has content
          if [ ! -d "wiki" ] || [ -z "$(ls -A wiki)" ]; then
            echo "No wiki directory or content found, skipping wiki update"
            echo "SKIP_WIKI=true" >> $GITHUB_ENV
            exit 0
          fi
          echo "Wiki content found, proceeding with update"
      
      - name: Clear and update wiki content
        if: env.SKIP_WIKI != 'true'
        run: |
          cd wiki-repo
          
          # Clear existing content (preserve .git directory)
          find . -type f ! -path "./.git/*" -delete
          find . -type d ! -path "./.git*" -empty -delete 2>/dev/null || true
          
          # Copy new content from wiki directory
          rsync -av --exclude='.git*' ${{ github.workspace }}/wiki/ ./
          
          # Add all changes
          git add . || true
      
      - name: Commit and push changes
        if: env.SKIP_WIKI != 'true'
        run: |
          cd wiki-repo
          
          # Configure git remote with token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes detected in wiki content"
            exit 0
          else
            echo "Changes detected, committing wiki updates..."
            git commit -m "Update wiki from ${{ github.sha }} - ${{ github.event.head_commit.message }}"
            git push origin master
            echo "Wiki updated successfully"
          fi
      
      - name: Summary
        run: |
          if [ "$SKIP_WIKI" = "true" ]; then
            echo "Wiki publishing skipped - no wiki content found"
          else
            echo "Wiki publishing completed"
          fi